apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h560vxoc9-nodejs
  janus-idp.io/tekton: h560vxoc9-nodejs
  backstage.io/kubernetes-id: h560vxoc9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h560vxoc9-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
